---
name: Anchore for vulnerability Scanning

on:
  push:
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch: 

jobs:
  test:
    name: Achore scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - centos
        python-version:
          - 3.8

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Scan current project
        uses: anchore/scan-action@v2
        with:
          path: "."

      - name: Build the container image
        run: sudo docker build -t csrinath321/demonodeapp:latest .

      - name: Scan the container image
        uses: anchore/scan-action@v2
        id: scan
        with:
          image: "csrinath321/demonodeapp:latest"
          acs-report-enable: true

      - name: upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      
      - name: Inspect action SARIF report
        run: cat ${{ steps.scan.outputs.sarif }}
      
      - name: printing directory content
        run: ls -R
      
      - name: grype scan JSON results
        run: for j in vulnerabilities.json; do echo "---- ${j} ----"; cat ${j}; echo; done
